version: '3'
services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: <PRIVATE-IP-ADDRESS>:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<PRIVATE-IP-ADDRESS>:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
